spring.application.name=plan-it
spring.data.mongodb.uri=mongodb+srv://satishbisa:hellohello123@cluster0.b7fpk09.mongodb.net/?retryWrites=true&w=majority&ssl=true&appname=Cluster0
spring.data.mongodb.database=plan-it_travel